version: '3.8'

services:
  postgres:
    image: postgres:14
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - static_volume:/app/myproject/staticfiles
      - ./frontend:/app/myproject/myapp/static/myapp
    depends_on:
      - postgres
    env_file: .env
    networks:
      - frontend
      - backend


  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - ./frontend:/usr/share/nginx/html/frontend
    ports:
      - "8443:8443"
    depends_on:
      - django
    networks:
      - frontend

volumes:
  postgres_data:
  static_volume:

networks:
  backend:
  frontend: