# Generated by Django 4.2.18 on 2025-01-20 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabPlayers', models.JSONField(default=list)),
                ('tabPlayersNewRound', models.JSONField(default=list)),
                ('numberMatchPlayed', models.IntegerField(default=0)),
                ('courtColor', models.CharField(default='0xCF5A30', max_length=8)),
                ('sizeTournament', models.IntegerField(default=0)),
                ('superPower', models.CharField(default='isSuperPower', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
