# Generated by Django 4.2.18 on 2025-01-27 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_onlineplayers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(default='Player1', max_length=20)),
                ('username2', models.CharField(default='Player2', max_length=20)),
                ('colorPlayer1', models.CharField(default='#E23F22', max_length=8)),
                ('colorPlayer2', models.CharField(default='#3BB323', max_length=8)),
                ('heroPowerPlayer1', models.CharField(default='Invisible', max_length=20)),
                ('heroPowerPlayer2', models.CharField(default='Super strength', max_length=20)),
                ('typeOfGame', models.CharField(default='multiplayer', max_length=20)),
                ('numberPlayers', models.IntegerField(default=0)),
                ('modeGame', models.CharField(default='multiPlayerTwo', max_length=40)),
                ('superPower', models.CharField(default='isSuperPower', max_length=20)),
                ('courtColor', models.CharField(default='0xCF5A30', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
