# Generated by Django 4.2.18 on 2025-01-30 10:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_matchuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamestatslocal',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, default=list, size=None),
        ),
    ]
