# Generated by Django 4.2.18 on 2025-01-30 13:14

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_gamestatslocal_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='match_history',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='gamestatslocal',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(default=datetime.date.today), blank=True, default=list, size=None),
        ),
        migrations.CreateModel(
            name='MatchHistoryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username1', models.CharField(default='Player1', max_length=20)),
                ('username2', models.CharField(default='Player2', max_length=20)),
                ('heroPlayer1', models.CharField(default='Invisible', max_length=20)),
                ('heroPlayer2', models.CharField(default='Super strength', max_length=20)),
                ('numberGameBreaker', models.IntegerField(default=0)),
                ('echangeLong', models.IntegerField(default=0)),
                ('dureeMatch', models.IntegerField(default=0)),
                ('vainqueur', models.CharField(default='Player1', max_length=20)),
                ('dates', models.DateField(default=datetime.date.today)),
                ('isSuperPower', models.CharField(default='isSuperPower', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_history_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
