# Generated by Django 4.2.18 on 2025-01-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_user_match_history_alter_gamestatslocal_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchhistoryuser',
            name='dureeMatch',
            field=models.FloatField(default=0.0),
        ),
    ]
